In [1]:
import pickle
import torch

# para_dir = "output/cheetah-dir/cheetah-dir_20220830030725-id1_seed100_srb/replay_buffer.pkl"
# para_dir = "output/cheetah-dir/cheetah-dir_20220830030725-id1_seed100_srb/params.pkl"
# para_dir = "output/cheetah-dir/cheetah-dir-20220908075447-id0_SAC_seed100_srb/params.pkl"
# para_dir = "output/cheetah-dir/cheetah-dir-20220908070026-id0_SAC_seed100_srb/params.pkl"
# para_dir = 'output/cheetah-dir/cheetah-dir-20220908090822-id0_SAC_seed100_srb/param_cheetah-dir_id0.pkl'
para_dir = 'output/cheetah-dir/cheetah-dir-20220908120409-id0_SAC_seed100_srb/params_epoch5_cheetah-dir-id0.pkl'
# para_dir = "output/cheetah-dir/cheetah-dir-20220908120730-id1_SAC_seed100_srb/params_epoch5_cheetah-dir-id1.pkl"

# with open(para_dir, 'rb') as tf:
#     param = pickle.load(tf)

param = torch.load(para_dir)
print(type(param))
print(param.keys())

<class 'dict'>
dict_keys(['trainer/policy', 'trainer/qf1', 'trainer/qf2', 'trainer/target_qf1', 'trainer/target_qf2', 'exploration/policy', 'exploration/env', 'evaluation/policy', 'evaluation/env'])


In [2]:
env = param['evaluation/env']
print(dir(env))
print(dir(env._wrapped_env))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply_normalize_obs', '_obs_mean', '_obs_std', '_reward_scale', '_should_normalize', '_wrapped_env', 'action_space', 'close', 'estimate_obs_stats', 'horizon', 'metadata', 'observation_space', 'render', 'reset', 'reward_range', 'seed', 'spec', 'step', 'terminate', 'unwrapped', 'wrapped_env']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__redu

In [3]:
print(env._inixpos)
print(env._wrapped_env._inixpos)

print(env._idx)
print(env._wrapped_env._idx)

print(env._goal)
print(env._wrapped_env._goal)

0
0
0
0
1
1


In [9]:
import numpy as np

# buf_dir = "output/cheetah-dir/cheetah-dir-20220908075447-id0_SAC_seed100_srb/buffer_cheetah-dir_id0.npy"
buf_dir = "output/cheetah-dir/cheetah-dir-20220908120730-id1_SAC_seed100_srb/buffers_cheetah-dir-id1.npy"

buffers = np.load(buf_dir, allow_pickle='TRUE').item()
print(type(buffers))
print(isinstance(buffers, dict))
print(buffers.keys())
print(buffers['rewards'].shape)

<class 'dict'>
True
dict_keys(['observations', 'actions', 'rewards', 'terminals', 'next_observations', 'forward_vel', 'reward_ctrl', 'xposbefore', 'xposafter'])
(8000, 1)


In [ ]:
print(buffers['xposbefore'][:3])
print(buffers['xposafter'][:3])

In [ ]:
print(buffers['xposbefore'][-3:])
print(buffers['xposafter'][-3:])

In [ ]:
print(buffers['reward_ctrl'][:3])
print(buffers['reward_ctrl'][-3:])

In [5]:
ctrl_cost = -0.5 * 1e-1 * np.sum(np.square(buffers['actions']), axis=1).reshape(-1,1)
ctrl_cost.shape

(8000, 1)

In [ ]:
print(ctrl_cost[:3])
print(ctrl_cost[-3:])

In [6]:
rewards = buffers['forward_vel']*-1 + buffers['reward_ctrl']
rewards.shape

(8000, 1)

In [7]:
print(buffers['rewards'][:3])
print(buffers['rewards'][-3:])

[[-0.21247011]
 [-0.36463522]
 [-0.68507225]]
[[ 0.23133253]
 [-0.04410894]
 [ 0.02671548]]


In [8]:
print(rewards[:3])
print(rewards[-3:])

[[-0.14020538]
 [ 0.2291146 ]
 [ 0.46031229]]
[[-0.40673961]
 [-0.18087234]
 [-0.28673092]]


In [12]:
forward_vel = buffers['forward_vel']

_forward_vel = (buffers['xposafter'] - buffers['xposbefore']) / 0.05
_forward_vel.shape

(8000, 1)

In [13]:
print(_forward_vel[:3], forward_vel[:3])
print('====')
print(_forward_vel[-3:], forward_vel[-3:])

[[-0.03613236]
 [-0.29687491]
 [-0.57269227]] [[-0.03613236]
 [-0.29687491]
 [-0.57269227]]
====
[[0.31903607]
 [0.0683817 ]
 [0.1567232 ]] [[0.31903607]
 [0.0683817 ]
 [0.1567232 ]]
